######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 4 14:37:18 2014
######################################################################

TEMPLATE = app
TARGET = Cryptolator
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Encrypt.h Window.h
SOURCES += main.cpp Window.cpp Encrypt.cpp
